### ISSUE TITLE
Pype broken with scikit-lean 0.24

### ISSUE THREAD

**Issue by pwoller** [dmbee/seglearn#54]
When using `Pype` with scikit-lean version 0.24 I get the following error:

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/wllr/miniconda3/envs/py38/lib/python3.8/site-packages/seglearn/pipe.py", line 59, in __init__
    super(Pype, self).__init__(steps, memory)
  File "/home/wllr/miniconda3/envs/py38/lib/python3.8/site-packages/sklearn/utils/validation.py", line 74, in inner_f
    return f(**kwargs)
  File "/home/wllr/miniconda3/envs/py38/lib/python3.8/site-packages/sklearn/pipeline.py", line 118, in __init__
    self._validate_steps()
  File "/home/wllr/miniconda3/envs/py38/lib/python3.8/site-packages/sklearn/pipeline.py", line 157, in _validate_steps
    self._validate_names(names)
  File "/home/wllr/miniconda3/envs/py38/lib/python3.8/site-packages/sklearn/utils/metaestimators.py", line 70, in _validate_names
    invalid_names = set(names).intersection(self.get_params(deep=False))
  File "/home/wllr/miniconda3/envs/py38/lib/python3.8/site-packages/sklearn/pipeline.py", line 137, in get_params
    return self._get_params('steps', deep=deep)
  File "/home/wllr/miniconda3/envs/py38/lib/python3.8/site-packages/sklearn/utils/metaestimators.py", line 29, in _get_params
    out = super().get_params(deep=deep)
  File "/home/wllr/miniconda3/envs/py38/lib/python3.8/site-packages/sklearn/base.py", line 195, in get_params
    value = getattr(self, key)
AttributeError: 'Pype' object has no attribute 'scorer'
```

Example to reproduce the error:
- python=3.8
- scikit-learn=0.24
- seglearn=1.2.1

```python
from seglearn.transform import SegmentX
from seglearn.pipe import Pype

pipe = Pype([('segment', SegmentX())])   # will crash on creation
```

From a quick view on the seglearn's source code
https://github.com/dmbee/seglearn/blob/9000eee4a1edd7dbb0bc4c3b63970c1b71c77a31/seglearn/pipe.py#L58-L64
one solution could be to move the call of the super's `__init__` to the end

```python
def __init__(self, steps, scorer=None, memory=None):
    self.scorer = scorer
    self.N_train = None
    self.N_test = None
    self.N_fit = None
    self.history = None
    super(Pype, self).__init__(steps, memory)
```

**Comment by dmbee** [comment]
Thanks for pointing this out. I am happy to implement the fix tomorrow, or if you prefer to submit a pull request on the master branch that is also ok. Let me know? 
Cheers

**Comment by pwoller** [comment]
If have not already started with the fix I can submit a pull request in the next days.

**Comment by dmbee** [comment]
Damn unfortunately I fixed it already. Should be available in the latest patch on github or pypi. Let me know if you have any other issues. 

In future, you're more than welcome to submit a pull. Sorry I pulled the trigger on this one before your reply.
